services:
  telegram-bot:
    build: .
    environment:
      - BOT_USR
      - BOT_TOKEN
      - URL
      - MOODLE_URL
      - ADMIN_CHATID
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_USR=${POSTGRES_USER}
      - DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    depends_on:
      - db
    restart: unless-stopped