spring:
  datasource:
    username: ${DB_USR}
    password: ${DB_PASS}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: create
bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USR}
moodle:
  url: ${MOODLE_URL}