spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USR}
web:
  currenturl: ${URL}
moodle:
  url: ${MOODLE_URL}
server:
  error:
    include-message: always
logging:
  pattern:
    console: '%d{HH:mm}| %highlight(%-5level) ---| %logger{36} - %m{20}%n'