spring:
  datasource:
    username: ${DB_USR}
    password: ${DB_PASS}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: false
bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USR}
web:
  currenturl: ${URL}
moodle:
  url: ${MOODLE_URL}
server:
  error:
    include-message: always
