create table courses
(
    course_id   bigint not null primary key,
    course_name character varying(255),
    short_name  character varying(255),
    updated_at  timestamp without time zone
);

create table events
(
    id          bigint primary key not null generated by default as identity,
    event_id    bigint,
    module_name character varying(255),
    name        character varying(255),
    time_start  timestamp without time zone,
    url         character varying(255)
);

create table users
(
    id                    bigint  not null primary key generated by default as identity,
    chat_id               bigint,
    receive_notifications boolean not null,
    state                 character varying(255),
    token                 character varying(255),
    user_id               bigint
);

create table groups
(
    id         bigint not null primary key,
    name       character varying(255),
    updated_at timestamp without time zone
);

create table events_courses
(
    course_id bigint references courses (course_id),
    event_id  bigint not null primary key references events (id)
);

create table events_groups
(
    group_id bigint references groups(id),
    event_id bigint not null primary key references events (id)
);


create table user_groups
(
    group_id bigint not null references groups (id),
    user_id  bigint not null references users (id),
    primary key (group_id, user_id)
);

create table users_courses
(
    course_id bigint not null references courses (course_id),
    user_id   bigint not null references users (id),
    primary key (course_id, user_id)
);

create table users_events
(
    event_id bigint  not null references events (id),
    user_id  bigint  not null references users (id),
    notified boolean not null,
    primary key (event_id, user_id)
);
