create table user_chats
(
    id     bigint primary key generated by default as identity,
    chat_id bigint
);

create table user_chats_users
(
    user_id      bigint references users (id),
    user_chat_id bigint primary key references user_chats (id)
);